### PR TITLE
Add methods to update versions in Gradle file for Anbox.

### PR DESCRIPTION
**Pull request by alex-iotiq**
Applying following changes from https://github.com/jenkinsci/peass-ci-plugin/issues/171.

Set compileSdkVersion, minSdkVersion, targetSdkVersion and add multiDexEnabled

```groovy

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 29
        multiDexEnabled = true
    }
```

### CODE REVIEW

**Review by alex-iotiq — COMMENTED** [review]
Implementing these changes.

```groovy
android.packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/LICENSE.md'
    exclude 'META-INF/NOTICE.md'
    exclude 'META-INF/jing-copying.html'
    exclude 'META-INF/LICENSE-notice.md'
}
```

**Comment by DaGeRe** [comment]
Thanks for the PR.
This looks overall fine, but could you possibly provide a unit test for it? (Just like the other tests, which check whether the gradle editing works right) Otherwise, this will be hard to maintain in the long run.

**Comment by DaGeRe** [comment]
How is the state of the unit test? ;)

**Comment by metint** [comment]
Hi @DaGeRe, we fixed some issues about gradle editing and also added the corresponding unit tests. We had to use `androidlib.gradle` in the unit tests as the gradle file to be modified, otherwise `GradleTaskAnalyzer` class was not recognize it as an Android project.

On the other hand we also saw that some tests using `androidlib.gradle` was disabled since they required Android SDK. Currently the (new and old) tests in `TestBuildGradleExclusions` pass in our local environment.

Please let us know if further action is required regarding this PR.

**Comment by DaGeRe** [comment]
Thanks for the updates, this seems fine to me. I've approved the PR, so Github actions can run, and if this is successful, I'll merge.

**Comment by DaGeRe** [comment]
Looks fine overall, thanks for the PR, I'll merge this.

**Pull request merged**
