### PR TITLE
Add strictMode for AnboxTestExecutor

### PR DESCRIPTION
**Pull request by alex-iotiq**
Implements this https://github.com/DaGeRe/kieker-source-instrumentation-dagere/issues/2 for AnboxTestExecutor.

### CODE REVIEW

**Comment by DaGeRe** [comment]
Thanks for the PR. Does this work for you in the source instrumentation?
If yes, I'll publish a new source instrumentation release, and than you can adjust the PR and use the latest source instrumentation. Peass should not rely on Snapshots.

**Comment by alex-iotiq** [comment]
> Does this work for you in the source instrumentation?

Yes it does

**Comment by alex-iotiq** [comment]
But to build Peass-ci-plugin succesfully with those changes I need to downgrade `com.github.javaparser:javaparser-core:3.24.9`  version to `3.24.8` inside 
`de.dagere.kieker:kieker-source-instrumentation-library:1.15.16-SNAPSHOT`.

    Require upper bound dependencies error for com.github.javaparser:javaparser-core:3.24.8 paths to dependency are:
    +-de.peass:peass-ci:2.3.5-SNAPSHOT-999999-SNAPSHOT
      +-com.github.javaparser:javaparser-core:3.24.8
    and
    +-de.peass:peass-ci:2.3.5-SNAPSHOT-999999-SNAPSHOT
      +-de.dagere.peass:dependency:0.3.5-SNAPSHOT
        +-de.dagere.kieker:kieker-source-instrumentation-library:1.15.16-SNAPSHOT
          +-com.github.javaparser:javaparser-core:3.24.9
    and
    +-de.peass:peass-ci:2.3.5-SNAPSHOT-999999-SNAPSHOT
      +-de.dagere.peass:dependency:0.3.5-SNAPSHOT
        +-de.dagere.kopeme:kopeme-junit5:1.2.1
          +-de.dagere.kopeme:kopeme-core:1.2.1
            +-com.github.javaparser:javaparser-core:3.24.8

**Comment by DaGeRe** [comment]
I'll publish this tomorrow (hopefully). 
Downgrading the version in Peass-CI works, another solution is to include `com.github.javaparser:javaparser-core:3.24.9` as dependency in Peass-CI directly (the plugin checks for different dependency versions, in order to avoid problems due to dependency updates you are not aware of).

**Comment by DaGeRe** [comment]
I did the update, should work fine now.

**Pull request merged**
