### PR TITLE
[FIX] Ignore .java file extension for comparing paths in VersionDiff

### PR DESCRIPTION
**Pull request by stro18**
Required for using '-classFolder java'

### CODE REVIEW

**Comment by DaGeRe** [comment]
Thanks for the PR.

Could you elaborate why this is necessary? If you add `-classFolder java`, `VersionDiff` will identify something like `noSourceFolder/a/b/c/Example.java` as possible change in `addChange(final String currentFileName, final ExecutionConfig config)` (since it contains `java`), and then pass it to `addChange(final String currentFileName, final String containedPath, final int indexOf)`. But in the second method, the module should be considered to be `noSourceFolder/a/b/c/Example`, which is no legal module, and therefore the change should not be added.

**Comment by stro18** [comment]
Let's say we use '-classFolder java -testClassFolder test'. Then `config.getAllClazzFolders()` returns 'java' and 'test'. 
If `currentFileName` is 'test/a/b/c/CoyoteAdapter.java' the `containedPath` should be 'test' but in the old version it is 'java'. That is why in `addChange(final String currentFileName, final String containedPath, final int indexOf)` `moduleFile` is 'test/a/b/c/CoyoteAdapter` instead of ''.

**Comment by DaGeRe** [comment]
Thanks for the elaboration, this makes it clearer. However, just replacing `.java` could lead to a problem, for example if folders are named `sources.java` and `sources.scala`. Therefore, I adjusted the code so that exactly the ending (not all occurences of `.java`) is removed: https://github.com/DaGeRe/peass/commit/c2b0c1873b27dc2167a7b54059bd66a6ebe6a03b does this work for you?

**Comment by stro18** [comment]
Yes this should work.

**Comment by DaGeRe** [comment]
Cool, just contact me if there are further problems with this.

**Pull request closed without merging**
